# Generated by Django 5.1.6 on 2025-03-28 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CoalReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('load_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('tm', models.FloatField(blank=True, null=True)),
                ('im', models.FloatField(blank=True, null=True)),
                ('gcv', models.FloatField(blank=True, null=True)),
                ('ncv', models.FloatField(blank=True, null=True)),
                ('basis_of_measurement', models.CharField(choices=[('Load Port', 'Load Port'), ('Discharge Port', 'Discharge Port'), ('As Fired', 'As Fired'), ('Others', 'Others')], max_length=50)),
                ('other_basis', models.CharField(blank=True, max_length=255, null=True)),
                ('section', models.CharField(choices=[('proximate_analysis', 'Proximate Analysis'), ('ultimate_analysis_lab', 'Ultimate Analysis (LAB)'), ('ultimate_analysis_calc', 'Ultimate Analysis (CALC)'), ('petrography_analysis', 'Petrography Analysis'), ('ash_elementary_analysis', 'ASH ELEMENTARY ANALYSIS'), ('slagging_analysis', 'Slagging or Fouling Propensity')], max_length=50)),
                ('parameter', models.CharField(max_length=100)),
                ('arb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('adb', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('db', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remark_text', models.TextField()),
            ],
        ),
    ]
