# Generated by Django 5.1.6 on 2025-03-29 05:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mmr', models.CharField(max_length=255)),
                ('remark', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AshData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Moisture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('im', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='PetrographyData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='SlaggingData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='TableData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('arb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('db', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='UltimateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('arb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('db', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='VesselInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vessel_name', models.CharField(max_length=255)),
                ('vessel_type', models.CharField(max_length=255)),
                ('origin', models.CharField(max_length=255)),
                ('load_port', models.CharField(max_length=255)),
                ('destination_port', models.CharField(max_length=255)),
                ('gcv', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ncv', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.DeleteModel(
            name='CoalReport',
        ),
        migrations.AddField(
            model_name='ultimatedata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='tabledata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='petrographydata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='moisture',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='ashdata',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
        migrations.AddField(
            model_name='additionalinfo',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo'),
        ),
    ]
