# Generated by Django 5.1.6 on 2025-03-29 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_additionalinfo_ashdata_moisture_petrographydata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moisture',
            name='basis_of_measurement',
            field=models.CharField(blank=True, choices=[('Load Port', 'Load Port'), ('Discharge Port', 'Discharge Port'), ('As Fired', 'As Fired'), ('Others', 'Others')], default='', max_length=255),
        ),
        migrations.AddField(
            model_name='moisture',
            name='other_basis',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
