# Generated by Django 5.1.6 on 2025-03-29 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_moisture_basis_of_measurement_moisture_other_basis'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moisture',
            name='other_basis',
        ),
        migrations.AlterField(
            model_name='moisture',
            name='basis_of_measurement',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
