# Generated by Django 5.1.6 on 2025-03-29 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_moisture_other_basis_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vesselinfo',
            name='hgi',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
