# Generated by Django 5.1.6 on 2025-04-01 05:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_tabledata_fc_vm_adb_tabledata_fc_vm_arb_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UltimateData1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parameter', models.CharField(max_length=255)),
                ('arb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('adb', models.DecimalField(decimal_places=2, max_digits=10)),
                ('db', models.DecimalField(decimal_places=2, max_digits=10)),
                ('vessel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.vesselinfo')),
            ],
        ),
    ]
