# Generated by Django 5.1.6 on 2025-04-01 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_ultimatedata1'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinfo',
            name='mmr',
        ),
        migrations.RemoveField(
            model_name='slaggingdata',
            name='key',
        ),
        migrations.RemoveField(
            model_name='slaggingdata',
            name='parameter',
        ),
        migrations.RemoveField(
            model_name='slaggingdata',
            name='value',
        ),
        migrations.AddField(
            model_name='ashdata',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='petrographydata',
            name='mmr',
            field=models.CharField(default=0.0, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='petrographydata',
            name='total_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='petrographydata',
            name='vi_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='C1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='M1',
            field=models.DecimalField(blank=True, decimal_places=5, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='T250_temperature',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='base_acid_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='iron_calcium_ratio',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='iron_plus_calcium',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='silica_percent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='slagging_factor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='slagging_index',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatedata',
            name='dulong_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='ultimatedata1',
            name='dulong_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
