# Generated by Django 5.1.6 on 2025-04-07 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_additionalinfo_mmr_remove_slaggingdata_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slaggingdata',
            name='ash_fusion_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='hemispherical_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='slaggingdata',
            name='initial_deformation_temp',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
