# Generated by Django 5.1.6 on 2025-04-21 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_slaggingdata_ash_fusion_temp_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('columns', models.TextField()),
                ('rows', models.TextField(blank=True, default='[]')),
            ],
        ),
    ]
