# Generated by Django 5.1.6 on 2025-04-22 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabledata',
            name='boiler_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
