# Generated by Django 5.1.6 on 2025-04-22 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_tabledata_boiler_efficiency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabledata',
            name='boiler_efficiency',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
